create_clock -period 5.000 -name clk -waveform {0.000 2.500} [get_ports clk]

set_property PACKAGE_PIN K4 [get_port clk]

set_property PACKAGE_PIN K3 [get_port in_val]
set_property PACKAGE_PIN K2 [get_port oflag]
set_property PACKAGE_PIN K1 [get_port {G[0]}]
set_property PACKAGE_PIN J1 [get_port {G[1]}]
set_property PACKAGE_PIN J2 [get_port {G[2]}]
set_property PACKAGE_PIN J4 [get_port {G[3]}]
set_property PACKAGE_PIN J5 [get_port {G[4]}]
set_property PACKAGE_PIN L5 [get_port {G[5]}]
set_property PACKAGE_PIN L4 [get_port {G[6]}]
set_property PACKAGE_PIN L3 [get_port {G[7]}]
set_property PACKAGE_PIN L1 [get_port {G[8]}]
set_property PACKAGE_PIN M1 [get_port {G[9]}]

set_property PACKAGE_PIN M2 [get_port {L[0]}]
set_property PACKAGE_PIN M3 [get_port {L[1]}]
set_property PACKAGE_PIN M5 [get_port {L[2]}]
set_property PACKAGE_PIN M6 [get_port {L[3]}]
set_property PACKAGE_PIN N2 [get_port {L[4]}]
set_property PACKAGE_PIN N3 [get_port {L[5]}]
set_property PACKAGE_PIN N4 [get_port {L[6]}]
set_property PACKAGE_PIN N5 [get_port {L[7]}]
set_property PACKAGE_PIN P1 [get_port {L[8]}]
set_property PACKAGE_PIN P2 [get_port {L[9]}]


set_property PACKAGE_PIN R1 [get_port {A[0]}]
set_property PACKAGE_PIN R2 [get_port {A[1]}]
set_property PACKAGE_PIN R3 [get_port {A[2]}]
set_property PACKAGE_PIN R4 [get_port {A[3]}]
set_property PACKAGE_PIN R6 [get_port {A[4]}]
set_property PACKAGE_PIN T1 [get_port {A[5]}]
set_property PACKAGE_PIN T3 [get_port {A[6]}]
set_property PACKAGE_PIN T4 [get_port {A[7]}]
set_property PACKAGE_PIN T5 [get_port {A[8]}]
set_property PACKAGE_PIN T6 [get_port {A[9]}]
set_property PACKAGE_PIN U1 [get_port {A[10]}]
#set_property PACKAGE_PIN U2 [get_port {A[11]}]