# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tfbg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.cache/wt} [current_project]
set_property parent.project_path {D:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/new/Azimuth.vhd}
  {D:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/new/Top_module.vhd}
}
read_ip -quiet {{D:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc}}]

read_ip -quiet {{D:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/ip/cordic_0/cordic_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/ip/cordic_0/cordic_0_ooc.xdc}}]

read_ip -quiet {{D:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/ip/div_gen_0/div_gen_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/ip/div_gen_0/div_gen_0_ooc.xdc}}]

read_ip -quiet {{D:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/ip/cordic_1/cordic_1.xci}}
set_property used_in_implementation false [get_files -all {{d:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/ip/cordic_1/cordic_1_ooc.xdc}}]

read_ip -quiet {{D:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/ip/cordic_sqrt/cordic_sqrt.xci}}
set_property used_in_implementation false [get_files -all {{d:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/ip/cordic_sqrt/cordic_sqrt_ooc.xdc}}]

read_ip -quiet {{D:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/ip/mult_gen_0/mult_gen_0_ooc.xdc}}]

read_ip -quiet {{D:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/ip/mult_gen_1/mult_gen_1.xci}}
set_property used_in_implementation false [get_files -all {{d:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/sources_1/ip/mult_gen_1/mult_gen_1_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/constrs_1/new/const1.xdc}}
set_property used_in_implementation false [get_files {{D:/Projects/probation training/cordic_Azimuth/cordic_Azimuth.srcs/constrs_1/new/const1.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top_module -part xc7a200tfbg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_module_utilization_synth.rpt -pb Top_module_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
